HotelProject/HotelMVC/HotelMVC/Controllers/RoomController.cs
using HotelMVC.Models;
using HotelMVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelMVC.Controllers
{
    public class RoomController : Controller
    {
        RoomService RoomStore;

        public RoomController(RoomService _RoomStore)
        {
            RoomStore = _RoomStore;
        }
       


        // GET: Room
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Booking()
        {
            BooKingForm FormData = new BooKingForm {
                categories = RoomStore.GetAllcategories(),
                Beds= RoomStore.GetAllBeds()
            };
       

            return View(FormData);
        }
        [HttpPost]
        public ActionResult ConfirmBooking(BooKingDataForm FormData)
        {
            if (FormData.StartDate < FormData.EndDate)
            {
                int result = RoomStore.CheckForReservation(FormData);
                if (result > 0)
                {
                    RoomDetail RoomData  = RoomStore.GetRoomById(result);
                    ConfirmBooking Data = new ConfirmBooking
                    {
                        StartDate = FormData.StartDate,
                        EndDate = FormData.EndDate,
                        Room=new RoomsList {RoomId=RoomData.RoomDetailscode,RoomNum=RoomData.RoomNumber },
                        Price = RoomStore.RecervationPrice(FormData)
                    };
                    return View (Data);
                }
            }
            return View();

        }

      


    } 
}

HotelProject/HotelMVC/HotelMVC/Controllers/RoomReservationsController.cs
using HotelMVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HotelMVC.Controllers
{
    public class RoomReservationsController : Controller
    {

        RoomReservationService RoomReservationStore;
        GuestService GuestStore;
        RoomService RoomStore;

        public RoomReservationsController(RoomReservationService _RoomReservationStore, GuestService _GuestStore, RoomService _RoomStore)
        {
            RoomReservationStore= _RoomReservationStore;
            GuestStore = _GuestStore;
            RoomStore = _RoomStore;
        }

        // GET: RoomReservations
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> NewReservation(RoomReservation Reservation)
        {
            Reservation.GuestID = 1;
            Guest CheckGuest = GuestStore.GetGuestById(Reservation.GuestID);
            if (CheckGuest != null)
            {
                int CheckReservation = await RoomReservationStore.CreatNewReservation(Reservation);
                if (CheckReservation != 0)
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }
       
    }
}

HotelProject/HotelMVC/HotelMVC/Views/Room/Booking.cshtml
@model  HotelMVC.Models.BooKingForm
@{
    ViewBag.Title = "Booking";
}

<h2>Booking</h2>

<form id="form" action=" ConfirmBooking" method="post" class="form-group">

    <label for="Roomcategory">select room category</label>
    <select name="Category" class="form-control">
        @foreach (var item in Model.categories)
        {
            <option value="@item.CategoryId">@item.CategoryName</option>
        }
    </select>

    <label for="Bed">select number of beds </label>
    <select name="Bed" class="form-control">
        @foreach (var item in Model.Beds)
        {
            <option value="@item.BedsId">@item.BedsNum </option>
        }
    </select>

    <div class="form-group">
        <label for="StartDate">Enter StartDate</label>
        <input type="datetime" class="form-control" id="StartDate" name="StartDate" placeholder="Enter StartDate">
    </div>
    <div class="form-group">
        <label for="EndDate">Enter EndDate</label>
        <input type="datetime" class="form-control" id="EndDate" name="EndDate" placeholder="Enter EndDate">
    </div>

    <button type="submit"  class="btn btn-primary">Submit</button>
</form>

<div id="Confirm"></div>
    @*<script>
        function open() {
            $.ajax({
                url: 'room/Booking',
                contentType: 'application/json',
                type: 'POST',
                data: JSON.stringify($('#form').serializeArray().reduce(function (obj, item) {
                    obj[item.name] = item.value;
                    return obj;
                }, {})),
                success: function (view) {
                    $("#Confirm").empty();
                    $("#Confirm").append(view);
                    var n = $(document).height();
                    $('html, body').animate({ scrollTop: n }, 50);
                },
                error: function (error) {
                    console.log(error);
                }
            });
        }
    </script>*@

HotelProject/HotelMVC/HotelMVC/Views/Room/ConfirmBooking.cshtml
@model HotelMVC.Models.ConfirmBooking
@{
    ViewBag.Title = "ConfirmBooking";
}

<h2>ConfirmBooking</h2>
@if (Model != null)
{

    <form id="form" action="@Url.Action("NewReservation", "RoomReservations")" method="post" class="form-group">


        <input type="number" class="form-control" id="TotelPrice" name="GuestID" value="1" style="visibility: hidden">
        <label>StartDate : @Model.StartDate</label>
        <input type="datetime" class="form-control" id="StartDate" name="StartDate" value="@Model.StartDate" style="visibility: hidden">

        <label>EndDate  :@Model.EndDate</label>
        <input type="datetime" class="form-control" id="EndDate" name="EndDate" value="@Model.EndDate" style="visibility: hidden">

        <label>RoomNumber : @Model.Room.RoomNum</label>
        <input type="number" class="form-control" id="RoomID" name="RoomID" value="@Model.Room.RoomId" style="visibility: hidden">

        <label>TotelPrice : @Model.Price</label>
        <input type="number" class="form-control" id="TotelPrice" name="TotelPrice" value="@Model.Price" style="visibility: hidden">

        <button type="submit" class="btn btn-primary">Confirm Booking</button>
    </form>
}
else
{
    <label> Not Avilable in this Date</label>

}